/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PhotoVaultRouteImport } from './routes/photo-vault'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as PhotoVaultAlbumRouteImport } from './routes/photo-vault.$album'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoVaultRoute = PhotoVaultRouteImport.update({
  id: '/photo-vault',
  path: '/photo-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoVaultAlbumRoute = PhotoVaultAlbumRouteImport.update({
  id: '/$album',
  path: '/$album',
  getParentRoute: () => PhotoVaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/photo-vault': typeof PhotoVaultRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/photo-vault/$album': typeof PhotoVaultAlbumRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/photo-vault': typeof PhotoVaultRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/photo-vault/$album': typeof PhotoVaultAlbumRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/photo-vault': typeof PhotoVaultRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/photo-vault/$album': typeof PhotoVaultAlbumRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/photo-vault'
    | '/terms'
    | '/thank-you'
    | '/photo-vault/$album'
    | '/trips/$slug'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/photo-vault'
    | '/terms'
    | '/thank-you'
    | '/photo-vault/$album'
    | '/trips/$slug'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/photo-vault'
    | '/terms'
    | '/thank-you'
    | '/photo-vault/$album'
    | '/trips/$slug'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PhotoVaultRoute: typeof PhotoVaultRouteWithChildren
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TripsSlugRoute: typeof TripsSlugRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-vault': {
      id: '/photo-vault'
      path: '/photo-vault'
      fullPath: '/photo-vault'
      preLoaderRoute: typeof PhotoVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-vault/$album': {
      id: '/photo-vault/$album'
      path: '/$album'
      fullPath: '/photo-vault/$album'
      preLoaderRoute: typeof PhotoVaultAlbumRouteImport
      parentRoute: typeof PhotoVaultRoute
    }
  }
}

interface PhotoVaultRouteChildren {
  PhotoVaultAlbumRoute: typeof PhotoVaultAlbumRoute
}

const PhotoVaultRouteChildren: PhotoVaultRouteChildren = {
  PhotoVaultAlbumRoute: PhotoVaultAlbumRoute,
}

const PhotoVaultRouteWithChildren = PhotoVaultRoute._addFileChildren(
  PhotoVaultRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PhotoVaultRoute: PhotoVaultRouteWithChildren,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TripsSlugRoute: TripsSlugRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
